name: "Set up dependencies"
description: "Sets up system and package dependencies"

runs:
  using: "composite"
  steps:
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: "release"

    - uses: r-lib/actions/setup-pandoc@v2

    - name: Query dependencies
      working-directory: pharmr_repo
      run: |
        install.packages('remotes')
        saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
      shell: Rscript {0}

    - uses: actions/setup-python@v5
      with:
          python-version: "3.12"

    - name: Install system dependencies
      working-directory: pharmr_repo
      if: runner.os == 'Linux'
      run: |
        while read -r cmd
        do
          eval sudo $cmd
        done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "22.04"))')
        sudo apt install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libicu-dev
      shell: bash

    - name: Install png (temporary)
      working-directory: pharmr_repo
      if: runner.os == 'Windows'
      run: |
        install.packages('png', repos='https://mran.microsoft.com/snapshot/2022-11-27')
      shell: Rscript {0}

    - name: Install R packages
      working-directory: pharmr_repo
      run: |
        remotes::install_deps(dependencies = TRUE)
        remotes::install_cran("rcmdcheck")
        install.packages('reticulate')
        install.packages('devtools')
        install.packages('promises')
        install.packages('stringi')
        remotes::install_local(force=TRUE)
      shell: Rscript {0}

